# library used (install.package if don't have)
library(mice)
library(VIM)
library(corrplot)
library(psych)
library(lattice)

# capture the parameters to opar
opar <- par(no.readonly = TRUE)

#-------------------------------------------------------------------------------
# Data Preparation
#-------------------------------------------------------------------------------

# read csv file into a dataframe
stroke_data <- read.csv("stroke.csv", na = "")

stroke_data

# Check duplicate data
sum(duplicated(stroke_data))

# Examine the data type and 
# show the structure of dataframe
str(stroke_data)

# Noted bmi is chr because of "N/A"

# Change N/A of bmi to NA
# and convert bmi from chr to numerical
stroke_data$bmi[stroke_data$bmi == "N/A"] <- NA

stroke_data$bmi <- as.numeric(stroke_data$bmi)

# Check class of bmi
class(stroke_data$bmi)

# Convert the Date to date str
# by using as.Date()
# Using "%A %d %B %Y"
# %A is unabbreviated weekday; %d is day; 
# %B is unabbreviated month; %Y is 4-digit year
stroke_data$Date <- as.Date(stroke_data$Date, "%A %d %B %Y")

# Create new col named weekday
# that contains day of the week
# using weekdays() to extract the weekday of the date
stroke_data$weekday <- weekdays(stroke_data$Date)

# Convert all the chr class variables to factor for plot
stroke_data$gender <- factor(stroke_data$gender)
stroke_data$ever_married <- factor(stroke_data$ever_married)
stroke_data$work_type <- factor(stroke_data$work_type, 
                                levels = c("Never_worked", 
                                           "children", 
                                           "Govt_job", 
                                           "Private", 
                                           "Self-employed"), 
                                labels = c("never worked", 
                                           "children", 
                                           "govt job", 
                                           "private", 
                                           "self-employed"))
stroke_data$Residence_type <- factor(stroke_data$Residence_type)
stroke_data$smoking_status <- factor(stroke_data$smoking_status, 
                                     levels = c("never smoked", 
                                                "formerly smoked", 
                                                "smokes", 
                                                "Unknown"), 
                                        labels = c("never smoked", 
                                                   "formerly smoked", 
                                                   "smokes", 
                                                   "unknown"))

# hypertension, heart_disease and stroke
# need to converted to factor as categorical data
stroke_data$hypertension_factor <- factor(stroke_data$hypertension, 
                                   labels = c("no", "yes"))
stroke_data$heart_disease_factor <- factor(stroke_data$heart_disease, 
                                    labels = c("no", "yes"))
stroke_data$stroke_factor <- factor(stroke_data$stroke, 
                             labels = c("healthy", "stroke"))

# use summary() to check the transformation
# weekday just show the recorded days
# so no need to convert it
summary(stroke_data)

# Use mice and VIM package
# to show the missing values
md.pattern(stroke_data, rotate.names = TRUE)

missing_values <- aggr(stroke_data, 
                       prop = FALSE, 
                       numbers = TRUE, 
                       cex.axis = 0.5)

# summary of missing_values
summary(missing_values)

# 4% BMI data missing

# Use !complete.case to get the missing data
# and store in incomplete_data
incomplete_data <- stroke_data[!complete.cases(stroke_data),]
nrow(incomplete_data)

# use na.omit() to drop the missing data
# and check the NA
stroke_data <- na.omit(stroke_data)
sum(is.na(stroke_data))

# Use sapply() and is.numeric
# to get the list of numerical data
numeric_variable_list <- sapply(stroke_data, is.numeric)

# drop id column due meaningless 
# change it to FALSE
numeric_variable_list["id"] <- FALSE

# Create a subset of a dataframe
# containing only numerical data
stroke_numerical_data <- stroke_data[numeric_variable_list]

# change the column names for numerical data
# to improve display of corrplot
colnames(stroke_numerical_data)[
  colnames(stroke_numerical_data) == "avg_glucose_level"
  ] <- "glucose"

colnames(stroke_numerical_data)[
  colnames(stroke_numerical_data) == "heart_disease"
  ] <- "HD"

colnames(stroke_numerical_data)[
  colnames(stroke_numerical_data) == "hypertension"
  ] <- "HTN"

corrplot(cor(stroke_numerical_data), 
         order = 'AOE', 
         addCoef.col = 'black', 
         tl.pos = 'd',
         number.cex = 0.8)

# do.call() function allows us to 
# apply the cbind() to each element generated by
# lapply()
numerical_summary <- do.call(cbind, 
                             lapply(stroke_numerical_data[c(1, 4, 5)], 
                                    summary))
numerical_summary

# examine the data in more detail
# showing age, glucose and bmi with pairs
pairs(stroke_numerical_data[c(1, 4, 5)])

pairs.panels(stroke_data[c(2, 3, 6, 7, 8, 9, 10, 11,15, 16, 17)],
             smooth = TRUE,
             scale = FALSE,
             density = TRUE,
             ellipses = TRUE,
             method = "spearman",
             pch = 21,
             lm = FALSE, 
             cor = TRUE,
             jiggle = FALSE,
             factor = 2,
             hist.col = 4,
             stars = TRUE,
             ci = TRUE) 

#-------------------------------------------------------------------------------
# Data Visualisation
# Percentage of Stroke vs Healthy
#-------------------------------------------------------------------------------

# check the healthy patient records
# and stroke patient records
nrow(stroke_data[stroke_data$stroke_factor == "healthy", ])
nrow(stroke_data[stroke_data$stroke_factor == "stroke", ])

# table of percentage of stroke vs healthy
# called percentage_table
percentage_stroke_healthy <- round(
  prop.table(table(stroke_data$stroke_factor)) * 100
  )

# barplot the percentage of patient had stroke vs healthy
# red = stroke,  blue = healthy
barplot(percentage_stroke_healthy, 
        col = c("blue", "red"), 
        main = "Percentage of patient - healthy vs stroke", 
        ylab = "Percentage", 
        ylim = c(0,105))
axis(2, at = 0:100 * 10)
text(0.65, 95, labels = percentage_stroke_healthy["healthy"],
     pos = 3)
text(0.73, 95, labels = "%",
     pos = 3)
text(1.85, 5, labels = percentage_stroke_healthy["stroke"],
     pos = 3)
text(1.91, 5, labels = "%",
     pos = 3)

#-------------------------------------------------------------------------------
# Research Question 1: 
# Does age has impact on stroke?
#-------------------------------------------------------------------------------

# Histogram to show the 
# distribution of age with stroke variable
# - Stroke vs Healthy
histogram(~ age | stroke_factor, 
          data = stroke_data, 
          main = "Distribution of age - healthy vs stroke", 
          xlab = "Age of patient", 
          ylab = "Frequency %")

# Using tapply & median 
# to get the median of both variables
tapply(stroke_data$age, stroke_data$stroke_factor, median)

# Q-Q plot of the age
# to check the normality
qqnorm(stroke_data$age, 
       main = "Normal Q-Q plot for age data")
qqline(stroke_data$age, col = "red")

# qqplot to comparing age variable
# and stroke variable
with(stroke_data, qqplot(age[stroke_factor == "stroke"], 
                         age[stroke_factor == "healthy"], 
                         main = "Comparing age variable and stroke variable", 
                         xlab = "Age of stroke patient",
                         ylab =  "Age of healthy patient"))

# plot in 1 row with 2 col
par(mfrow = c(1,2))

# Q-Q plot for distribution of age - the healthy patient
with(stroke_data, {qqnorm(age[stroke_factor == "healthy"], 
                          main = "Q-Q plot - Age of healthy patient") 
  qqline(age[stroke_factor == "healthy"], col = "red")})

# Q-Q plot for distribution of age - the stroke patient
with(stroke_data, {qqnorm(age[stroke_factor == "stroke"], 
                          main = "Q-Q plot - Age of stroke patient") 
  qqline(age[stroke_factor == "stroke"], col = "red")})

# reset parameter
par(opar)

# applying shapiro.test on age variable
# to check the normality
normality_test_Q1 <- shapiro.test(stroke_data$age)
normality_test_Q1$p.value

# p-values = 1.27e-31 < 0.05
# concluded dependent age variable is not normally distributed
# so choose non-parametric test

# dependent = continuous 
# independent = categorical
# non-parametric test
# Hence applying Mann-Whitney test
statistical_test_Q1 <- wilcox.test(stroke_data$age ~ stroke_data$stroke_factor)
statistical_test_Q1$p.value

# p-value = 6.20026e-61 (p-value < 0.05)
# null hypothesis is rejected

#-------------------------------------------------------------------------------
# Research Question 2: 
# Does smoking cause stroke?
#-------------------------------------------------------------------------------

# due to "unknown" is undefined data in smoking_status
# it will impact the testing
# so remove it
# and store in new data frame called research_Q2_test
research_Q2_test <- stroke_data[!stroke_data$smoking_status == "unknown", ]

# reset the factor of smoking_status
# to allow variable use in table() and chisq.test()
research_Q2_test$smoking_status <- factor(research_Q2_test$smoking_status)

# histogram of distribution between 
# smoking_status variable and stroke variable
# with Healthy vs Stroke
histogram(~ smoking_status | stroke_factor, 
          data = research_Q2_test, 
          main = "Distribution of smoking status - healthy vs stroke", 
          xlab = "Smoking status", 
          ylab = "Frequency %")

attach(research_Q2_test)
# apply chisq.test 
chisq.test(table(smoking_status, stroke_factor))
detach(research_Q2_test)

# p-value = 0.04996
# really close to 0.05
# decision can go either way

#-------------------------------------------------------------------------------
# Research Question 3: 
# Is body mass index (BMI) greater than or equal to 25 
# is highly chance to have stroke?
#-------------------------------------------------------------------------------

# histogram for distribution of bmi and stroke variable
# with stroke vs heathly
histogram(~stroke_data$bmi | stroke_data$stroke_factor, 
          main = "Distribution of bmi - healthy vs stroke", 
          xlab = "Body mass index (BMI)", 
          ylab = "Fequency %")

# check the median to check normality
tapply(stroke_data$bmi, stroke_data$stroke_factor, median)

# Q-Q plot for bmi data
qqnorm(stroke_data$bmi, 
       main = "Normal Q-Q plot of bmi data")
qqline(stroke_data$bmi, col = "red")

# Q-Q plot for comparing BMI variable and stroke variable
# with stroke and healthy
with(stroke_data,
     qqplot(bmi[stroke_factor == "stroke"],
            bmi[stroke_factor == "healthy"], 
            main = "Comparing bmi variable and stroke variable", 
            xlab = "BMI stroke patient",
            ylab =  "BMI healthy patient"))

# plot in 1 row with 2 col
par(mfrow = c(1, 2))

# Q-Q plot for the distribution of bmi
# healthy patient
with(stroke_data, {qqnorm(bmi[stroke_factor == "healthy"], 
                          main = "Q-Q plot bmi of healthy patient") 
  qqline(bmi[stroke_factor == "healthy"], col = "red")})

# Q-Q plot for the distribution of bmi
# stroke patient
with(stroke_data, {qqnorm(bmi[stroke_factor == "stroke"], 
                          main = "Q-Q plot age of stroke patient") 
  qqline(bmi[stroke_factor == "stroke"], col = "red")})

par(opar)

# apply Shapiro test on bmi var
# to check the normality
normality_test_Q3 <- shapiro.test(stroke_data$bmi)
normality_test_Q3$p.value

# p-value = 6.615873e-37 < 0.05
# bmi var is not normally distributed
# choose non-parametric test

# dependent = continuous 
# independent = categorical
# non-parametric test
# Hence applying Mann-Whitney test
# mu - specifying a parameter used to form null hypothesis
# alt - specifying the alternative hypothesis 
# one of "two.sided" (default), "greater" or "less"
wilcox.test(stroke_data$bmi ~ stroke_data$stroke_factor, 
            mu = 25, alternative = "greater")

# p-value = 1 (p-value > 0.05)
# null hypothesis is failed to reject

#-------------------------------------------------------------------------------
# Research Question 4: 
# Does a risk in BMI come with risk in blood glucose levels?
#-------------------------------------------------------------------------------

# plot the comparison of average glucose level
# with bmi
plot(stroke_data$bmi, 
     stroke_data$avg_glucose_level, 
     col = "blue", 
     main = "Comparison of average glucose level with bmi", 
     xlab = "BMI", 
     ylab = "Blood glucose level (Average)")

# histogram of avg_glucose_level
hist(stroke_data$avg_glucose_level, 
     main = "Histogram of average glucose level", 
     col = "blue", 
     xlab = "Average glucose level (blood)")

# plot in 1 row with 2 col
par(mfrow = c(1,2))

# Q-Q plot for distribution of bmi variable
# show qqline with red color 
with(stroke_data, {qqnorm(bmi, 
                   main = "Normal Q-Q plot of bmi data", 
                   xlab = "Body mass index (BMI)")
  qqline(bmi, col = "red")})

# Q-Q plot for distribution of average glucose level
# show qqline with red color
with(stroke_data, {qqnorm(avg_glucose_level, 
                   main = "Normal Q-Q plot of average of blood glucose levels", 
                   xlab = "Blood glucose levels (Average)")
  qqline(avg_glucose_level, col = "red")})

par(opar)

# Shapiro normality test for bmi
normality_test_Q4_bmi <- shapiro.test(stroke_data$bmi)
normality_test_Q4_bmi$p.value

# p-value = 6.615873e-37 < 0.05
# bmi variable is not normally distributed

# Shapiro normality test for avg_glucose_level
normality_test_Q4_glucose <- shapiro.test(stroke_data$avg_glucose_level)
normality_test_Q4_glucose$p.value

# p-value = 1.173727e-60
# avg_glucose_level is not normally distributed

# dependent variable - bmi (not normally distributed)
# non-parametric test will be applied
# Spearman’s Correlation Co-efficient implemented on both var
cor.test(stroke_data$bmi, stroke_data$avg_glucose_level, 
         method = "spearman", exact = FALSE)

# p-value = 9.16e-16
# p-value < 0.05, rejected null hypothesis

#-------------------------------------------------------------------------------
# Research Question 5: 
# Does high blood pressure (hypertension) lead to heart disease
#-------------------------------------------------------------------------------

attach(stroke_data)

# histogram of distribution of hypertension
# with heart disease
histogram(~hypertension_factor | heart_disease_factor, 
          main = "Distribution of hypertension vs heart disease", 
          xlab = "Hypertension", 
          ylab = "Fequency %")

# check percentage of patients
# have hypertension vs no hypertension
# by heart disease = yes
prop.table(table(
  hypertension_factor[heart_disease_factor == "yes"], 
  heart_disease_factor[heart_disease_factor == "yes"]
))

# patients have heart disease
# percentage of no hypertension = 76%
# percentage of hypertension = 24%

# check percentage of patients
# have hypertension vs no hypertension
# by heart disease = no
prop.table(table(
  hypertension_factor[heart_disease_factor == "no"], 
  heart_disease_factor[heart_disease_factor == "no"]
))

# patients no heart disease
# percentage of no hypertension = 92%
# percentage of hypertension = 8%

# apply chisq.test 
chisq.test(table(hypertension_factor, heart_disease_factor))
           
detach(stroke_data)

# p-value = 1.12e-15 < 0.05
# rejected null hypothesis



# Write stroke file as csv file for future work
write.csv(stroke_data, file = "Stroke-modified.csv")
